name: install

on:
  schedule:
  - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
    job1:
        name: setup
        runs-on: ubuntu-20.04
        steps:
            - name: basic install
              run: |
                  sudo apt install make ansible
            - name: ansible version
              run: |
                   ansible-playbook --version
            - uses: actions/checkout@v2-beta
            - name: install role via ansible-garaxy
              run: ansible-galaxy install rarrais.ros2
            - name: ansible
              run: |
                  ansible-playbook -i ansible/hosts/localhost.ini ansible/setup.yaml --connection local --become
            - name: install this tool
              run : python3 setup.py install
            - name: Slack Notification
              uses: 8398a7/action-slack@v2
              with:
                status: ${{ job.status }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}